plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Rails:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"
    "%r": "()"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/NumberedParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/MinMaxComparison:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Enabled: false

Metrics/AbcSize:
  Max: 40
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/WhereRange:
  Enabled: false

Rails/EnumSyntax:
  Enabled: true

Rails/EnumHash:
  Enabled: true
